[package]

name = "borealis"
version = "0.0.1"
authors = ["wbthomason <wil.thomason@gmail.com>"]

[dependencies.docopt]
git = "https://github.com/docopt/docopt.rs"

[dependencies.docopt_macros]
git = "https://github.com/docopt/docopt.rs"
