[package]

name = "bork"
version = "0.0.1"
authors = ["wbthomason <wil.thomason@gmail.com>"]

[dependencies]
curl            = "~0.3.4"
clap            = "~2.10.0"
toml            = "~0.2.0"
term            = "~0.4.4"
log             = "~0.3.6"
log4rs          = { version = "~0.4.8", features = ["toml", "yaml"] }
serde_json      = "~0.8.1"
serde_macros    = "~0.8.2"
libc            = "~0.2.15"
