[package]

name = "borealis"
version = "0.0.1"
authors = ["wbthomason <wil.thomason@gmail.com>"]

[dependencies]
hyper           = "0.6.5"
clap            = "1.1.4"
yaml-rust       = "0.2.1"
rustc-serialize = "0.3.15"
term            = "0.2.11"
