[package]

name = "bork"
version = "0.0.1"
authors = ["wbthomason <wil.thomason@gmail.com>"]

[dependencies]
curl            = "~0.3.4"
clap            = "~2.10.0"
toml            = "~0.2.0"
term            = "~0.4.4"
