refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  logf:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
